version: '2' 

networks:
   fabric-host2:

services:
   peer1-org1:
      container_name: peer1-org1.inuit.local
      image: hyperledger/fabric-peer
      environment:
         - CORE_PEER_ID=peer1-org1.inuit.local
         - CORE_PEER_ADDRESS=peer1-org1.inuit.local:7051
         - CORE_PEER_LOCALMSPID=org1MSP
         - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/org1/peer1/msp
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-proj_fabric-host2 # Starts chaincode containers on the same bridge network as peer
         - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
         - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbp1o1:5984
         - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1-org1
         - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=p1o1cdbpw
         - FABRIC_LOGGING_SPEC=debug
         - CORE_PEER_TLS_ENABLED=true
         - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/org1/peer1/tls-msp/signcerts/cert.pem
         - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/org1/peer1/tls-msp/keystore/p1o1-tls-key.pem
         - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/org1/peer1/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - OORE_PEER_GOSSIP_USELEADERELECTION=true
         - CORE_PEER_GOSSIP_ORGLEADER=false
         - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org1.inuit.local:7051
         - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
         - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer1
      volumes:
         - /var/run:/host/var/run
         - /etc/hyperledger/org1/peer1:/etc/hyperledger/org1/peer1
         - /etc/hyperledger/misc:/etc/hyperledger/misc
      depends_on:
         - couchdbp1o1
      extra_hosts:
         - "ca-tls.inuit.local:192.168.176.101"
         - "rca-org0.inuit.local:192.168.176.101"
         - "rca-org1.inuit.local:192.168.176.101"
         - "peer2-org1.inuit.local:192.168.176.104"
         - "peer2-org2.inuit.local:192.168.176.104"
         - "ord2-org1.inuit.local:192.168.176.104"
         - "cli-org0.inuit.local:192.168.176.104"
         - "peer1-org2.inuit.local:192.168.176.105"
         - "rca-org2.inuit.local:192.168.176.105"
         - "ord1-org2.inuit.local:192.168.176.105"
         - "cli-org2.inuit.local:192.168.176.105"
      networks:
         - fabric-host2
      ports:
         - 7051:7051
         - 7053:7053

   couchdbp1o1:
      container_name: couchdbp1o1
      image: hyperledger/fabric-couchdb
      environment:
         - COUCHDB_USER=peer1-org1
         - COUCHDB_PASSWORD=p1o1cdbpw
      ports:
         - "5984:5984"
      networks:
         - fabric-host2

   ord1-org1:
      container_name: ord1-org1.inuit.local
      image: hyperledger/fabric-orderer:1.4.2
      environment:
         - ORDERER_HOME=/etc/hyperledger/orderer
         - ORDERER_HOST=ord1-org1.inuit.local
         - ORDERER_GENERAL_LISTENADDRESS=ord1-org1.inuit.local
         - ORDERER_GENERAL_GENESISMETHOD=file
         - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/org1/ord1/genesis.block
         - ORDERER_GENERAL_LOCALMSPID=org1MSP
         - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/org1/ord1/msp
         - ORDERER_GENERAL_TLS_ENABLED=true
         - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/org1/ord1/tls-msp/signcerts/cert.pem
         - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/org1/ord1/tls-msp/keystore/key.pem
         - ORDERER_GENERAL_TLS_ROOTCAS=/etc/hyperledger/org1/ord1/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/org1/ord1/tls-msp/signcerts/cert.pem
         - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/org1/ord1/tls-msp/keystore/key.pem
         - ORDERER_GENERAL_CLUSTER_ROOTCAS=/etc/hyperledger/org1/ord1/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - ORDERER_GENERAL_LOGLEVEL=debug
         - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
         - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric
      command: orderer
      volumes:
         - /etc/hyperledger/org1/ord1:/etc/hyperledger/org1/ord1/
         - /etc/hyperledger/misc:/etc/hyperledger/misc
         - /orderer:/etc/hyperledger/orderer
      extra_hosts:
         - "ca-tls.inuit.local:192.168.176.101"
         - "rca-org0.inuit.local:192.168.176.101"
         - "rca-org1.inuit.local:192.168.176.101"
         - "peer2-org1.inuit.local:192.168.176.104"
         - "peer2-org2.inuit.local:192.168.176.104"
         - "ord2-org1.inuit.local:192.168.176.104"
         - "cli-org0.inuit.local:192.168.176.104"
         - "peer1-org2.inuit.local:192.168.176.105"
         - "rca-org2.inuit.local:192.168.176.105"
         - "ord1-org2.inuit.local:192.168.176.105"
         - "cli-org2.inuit.local:192.168.176.105"
      networks:
         - fabric-host2
      ports:
         - 7050:7050

   ord2-org2:
      container_name: ord2-org2.inuit.local
      image: hyperledger/fabric-orderer:1.4.2
      environment:
         - ORDERER_HOME=/etc/hyperledger/orderer
         - ORDERER_HOST=ord2-org2.inuit.local
         - ORDERER_GENERAL_LISTENADDRESS=ord2-org2.inuit.local
         - ORDERER_GENERAL_LISTENPORT=8050
         - ORDERER_GENERAL_GENESISMETHOD=file
         - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/org2/ord2/genesis.block
         - ORDERER_GENERAL_LOCALMSPID=org2MSP
         - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/org2/ord2/msp
         - ORDERER_GENERAL_TLS_ENABLED=true
         - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/org2/ord2/tls-msp/signcerts/cert.pem
         - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/org2/ord2/tls-msp/keystore/key.pem
         - ORDERER_GENERAL_TLS_ROOTCAS=/etc/hyperledger/org2/ord2/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/org2/ord2/tls-msp/signcerts/cert.pem
         - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/org2/ord2/tls-msp/keystore/key.pem
         - ORDERER_GENERAL_CLUSTER_ROOTCAS=/etc/hyperledger/org2/ord2/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - ORDERER_GENERAL_LOGLEVEL=debug
         - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
         - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric
      command: orderer
      volumes:
         - /etc/hyperledger/org2/ord2:/etc/hyperledger/org2/ord2/
         - /etc/hyperledger/misc:/etc/hyperledger/misc
         - /orderer:/etc/hyperledger/orderer
      extra_hosts:
         - "ca-tls.inuit.local:192.168.176.101"
         - "rca-org0.inuit.local:192.168.176.101"
         - "rca-org1.inuit.local:192.168.176.101"
         - "peer2-org1.inuit.local:192.168.176.104"
         - "peer2-org2.inuit.local:192.168.176.104"
         - "ord2-org1.inuit.local:192.168.176.104"
         - "cli-org0.inuit.local:192.168.176.104"
         - "peer1-org2.inuit.local:192.168.176.105"
         - "rca-org2.inuit.local:192.168.176.105"
         - "ord1-org2.inuit.local:192.168.176.105"
         - "cli-org2.inuit.local:192.168.176.105"
      networks:
         - fabric-host2
      ports:
         - 8050:8050

   cli-org1:
      container_name: cli-org1.inuit.local
      image: hyperledger/fabric-tools
      tty: true
      stdin_open: true
      environment:
         - GOPATH=/opt/gopath
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - FABRIC_LOGGING_SPEC=DEBUG
         - CORE_PEER_ID=cli-org1.inuit.local
         - CORE_PEER_ADDRESS=peer1-org1.inuit.local:7051
         - CORE_PEER_LOCALMSPID=org1MSP
         - CORE_PEER_TLS_ENABLED=true
         - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/org1/peer1/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/org1/peer1/msp
         - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1
      command: sh
      volumes:
         - /etc/hyperledger/org1/peer1:/etc/hyperledger/org1/peer1
         - /etc/hyperledger/org1/peer1/assets/chaincode:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode/
         - /etc/hyperledger/org1/admin:/etc/hyperledger/org1/admin
      extra_hosts:
        - "ca-tls.inuit.local:192.168.176.101"
         - "rca-org0.inuit.local:192.168.176.101"
         - "rca-org1.inuit.local:192.168.176.101"
         - "peer2-org1.inuit.local:192.168.176.104"
         - "peer2-org2.inuit.local:192.168.176.104"
         - "ord2-org1.inuit.local:192.168.176.104"
         - "cli-org0.inuit.local:192.168.176.104"
         - "peer1-org2.inuit.local:192.168.176.105"
         - "rca-org2.inuit.local:192.168.176.105"
         - "ord1-org2.inuit.local:192.168.176.105"
         - "cli-org2.inuit.local:192.168.176.105"
      networks:
         - fabric-host2
