version: '2'

networks:
   fabric-host1:

services:
   ca-tls:
      container_name: ca-tls.inuit.local
      image: hyperledger/fabric-ca:1.4.0
      command: sh -c 'fabric-ca-server init -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
      environment:
         - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-tlsca/crypto
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_NAME=ca-tls.inuit.local
         - FABRIC_CA_SERVER_CSR_CN=ca-tls.inuit.local
         - FABRIC_CA_SERVER_CSR_HOSTS=ca-tls.inuit.local,localhost,0.0.0.0
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ~/hyperledger/tls/ca:/etc/hyperledger/fabric-tlsca
      networks:
         - fabric-host1
      ports:
         - 7052:7052

   rca-org0:
      container_name: rca-org0.inuit.local
      image: hyperledger/fabric-ca
      command: sh -c 'fabric-ca-server init -d -b rca-org0-admin:rca-org0-adminpw --port 7053'
      environment:
         - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-org0-rca/crypto
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_NAME=rca-org0.inuit.local
         - FABRIC_CA_SERVER_CSR_CA=rca-org0.inuit.local
         - FABRIC_CA_SERVER_CSR_HOSTS=rca-org0.inuit.local,localhost,0.0.0.0
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ~/hyperledger/org0/ca:/etc/hyperledger/fabric-org0-rca
      networks:
         - fabric-host1
      ports:
         - 7053:7053

   rca-org1:
      container_name: rca-org1.inuit.local
      image: hyperledger/fabric-ca
      command: sh -c 'fabric-ca-server init -d -b rca-org1-admin:rca-org1-adminpw --port 7054'
      environment:
         - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-org1-rca/crypto
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_NAME=rca-org1.inuit.local
         - FABRIC_CA_SERVER_CSR_CA=rca-org1.inuit.local
         - FABRIC_CA_SERVER_CSR_HOSTS=rca-org1.inuit.local,localhost,0.0.0.0
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ~/hyperledger/org1/ca:/etc/hyperledger/fabric-org1-rca
      networks:
         - fabric-host1
      ports:
         - 7054:7054
